### ISSUE TITLE
ga-migration: invalid yml file generated

### ISSUE THREAD

**Issue by avivace** [inveniosoftware/automation-tools#17]
Running the migration script on `invenio-queues` produces an invalid yml

**Comment by mvidalgarcia** [comment]
Have you run the latest version of the script?
Assuming that the problem is [this](https://github.com/inveniosoftware/invenio-queues/actions/runs/410913303/workflow), it should have been fixed by https://github.com/inveniosoftware/automation-tools/pull/16 (`Fix issue adding empty include: section in GA tests.yaml.`), namely [this part](https://github.com/inveniosoftware/automation-tools/pull/16/files#diff-1770e61f1ed4602b49e922c9c38ac78c64c08d19fc517f1b12d7c8b23730e5abR82).

Could you please confirm that this was the issue and verify if it's still happening with `automation-tools/ga-migration` latest `master`?

**Comment by avivace** [comment]
Looks like it doesn't happen anymore with #16 merged. Thanks!
